version: "3"
services:
  pg:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task_tracker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
