version: "3"
services:
  frontend:
    build: ./frontend/
    ports:
      - "80:5173"
    networks:
      - default
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app/
  pg:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=task_tracker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      - default
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  backend:
      image: erixest/p8.2-super
#      user: "1000:1000"
      depends_on:
        - pg
      volumes: #mount backend srcs with read-write, group and user id = 1000
        - ./backend:/var/www
        - ./backend/supervisord.conf:/etc/supervisor/supervisord.conf
      ports:
        - "8000:80"
